local ____exports = {}
local ____game = require("game.game")
local Game = ____game.Game
function ____exports.init(self)
    Manager.init_script()
    Game()
end
function ____exports.on_message(self, message_id, message, sender)
    Manager.on_message(self, message_id, message, sender)
end
function ____exports.final(self)
    Manager.final_script()
end
init = ____exports.init
on_message = ____exports.on_message
final = ____exports.final

